"""Sender rewriting with PostSRSd.

SRS keeps forwarded mail from failing the SPF check of the domain it is
forwarded from, by rewriting the envelope sender to the relay own domain.
"""

import pytest

from tests.helpers import (container_exec, listening_sockets, postconf,
                           process_running, restart, send)

SRS_DOMAIN = 'srs.example.com'
GENERATED_MARKER = '# Generated by postfix-relay from POSTSRSD_ environment variables'


@pytest.fixture
def srs_relay(postfix_factory):
    return postfix_factory(env={'POSTSRSD_SRS_DOMAIN': SRS_DOMAIN})


def test_envelope_sender_is_rewritten(srs_relay, mailpit):
    send(srs_relay, sender='sender@example.com', subject='rewritten')

    message = mailpit.wait_for_message('rewritten')

    # SRS0=<hash>=<timestamp>=<domain>=<user>@<srs domain>
    assert message['ReturnPath'].startswith('SRS0=')
    assert message['ReturnPath'].endswith(f'=example.com=sender@{SRS_DOMAIN}')

    # Only the envelope is rewritten, the visible From stays untouched.
    assert message['From']['Address'] == 'sender@example.com'

    # And the rewriting is reversible, otherwise a bounce sent back to that
    # address would have nowhere to go.
    assert container_exec(srs_relay, [
        "postmap", "-q", message['ReturnPath'], "tcp:127.0.0.1:10002"
    ]).strip() == 'sender@example.com'


def test_each_deployment_generates_its_own_secret(postfix_factory):
    """The image ships without a secret, deliberately.

    Two deployments sharing one could forge each other's return addresses, so
    the packaged /etc/postsrsd.secret is removed when the image is built.
    """
    first = postfix_factory(env={'POSTSRSD_SRS_DOMAIN': SRS_DOMAIN})
    second = postfix_factory(env={'POSTSRSD_SRS_DOMAIN': SRS_DOMAIN})

    secret = container_exec(first, ["cat", "/etc/postsrsd.secret"])

    assert secret.strip()
    assert container_exec(second, ["cat", "/etc/postsrsd.secret"]) != secret
    # And it is not handed to whoever can read the container log.
    assert secret.strip() not in first.get_logs()[0].decode()


def test_excluded_domains_are_not_rewritten(postfix_factory, mailpit):
    relay = postfix_factory(env={
        'POSTSRSD_SRS_DOMAIN': SRS_DOMAIN,
        'POSTSRSD_SRS_EXCLUDE_DOMAINS': 'excluded.example',
    })

    send(relay, sender='sender@excluded.example', subject='excluded')

    assert mailpit.wait_for_message('excluded')['ReturnPath'] == 'sender@excluded.example'


def test_secret_and_configuration_survive_a_restart(srs_relay, mailpit):
    """Return addresses stay valid across a restart.

    They are signed with the secret, and rewriting them with a new one would
    make the bounces sent to the old addresses undeliverable.
    """
    secret = container_exec(srs_relay, ["md5sum", "/etc/postsrsd.secret"]).split()[0]

    restart(srs_relay)

    assert container_exec(srs_relay, ["md5sum", "/etc/postsrsd.secret"]).split()[0] == secret

    defaults = container_exec(srs_relay, ["cat", "/etc/default/postsrsd"])
    # The generated block is replaced, not appended to a second time.
    assert defaults.count(GENERATED_MARKER) == 1
    # The file is sourced, so the last assignment is the one that counts: the
    # packaged SRS_DOMAIN=localdomain has to stay above ours.
    domains = [line for line in defaults.splitlines() if line.startswith('SRS_DOMAIN=')]
    assert domains[-1] == f'SRS_DOMAIN={SRS_DOMAIN}'

    send(srs_relay, sender='sender@example.com', subject='rewritten after restart')

    assert mailpit.wait_for_message('rewritten after restart')['ReturnPath'].startswith('SRS0=')


def test_a_mounted_secret_is_kept(postfix_factory):
    """Mounting the secret is how return addresses survive a recreation."""
    secret = 'ThisIsTheMountedSecret\n'

    relay = postfix_factory(env={'POSTSRSD_SRS_DOMAIN': SRS_DOMAIN},
                            files={'/etc/postsrsd.secret': secret})

    assert container_exec(relay, ["cat", "/etc/postsrsd.secret"]) == secret
    assert 'No SRS secret found' not in relay.get_logs()[0].decode()
    # Tightened on every start, a mounted one included: it signs the return
    # addresses and anyone who can read it can forge them.
    assert container_exec(relay, ["stat", "-c", "%a", "/etc/postsrsd.secret"]).strip() == '600'


def test_the_postsrsd_ports_can_be_changed(postfix_factory, mailpit):
    """Both ends move together: the postfix maps follow the postsrsd ports."""
    relay = postfix_factory(env={
        'POSTSRSD_SRS_DOMAIN': SRS_DOMAIN,
        'POSTSRSD_SRS_FORWARD_PORT': '11001',
        'POSTSRSD_SRS_REVERSE_PORT': '11002',
    })

    assert postconf(relay, 'sender_canonical_maps') == 'tcp:127.0.0.1:11001'
    assert postconf(relay, 'recipient_canonical_maps') == 'tcp:127.0.0.1:11002'

    send(relay, sender='sender@example.com', subject='rewritten on another port')

    message = mailpit.wait_for_message('rewritten on another port')

    assert message['ReturnPath'].startswith('SRS0=')


def test_user_supplied_canonical_maps_are_kept(postfix_factory):
    """SRS only fills in the canonical maps the user did not set."""
    relay = postfix_factory(env={
        'POSTSRSD_SRS_DOMAIN': SRS_DOMAIN,
        'POSTFIX_sender_canonical_maps': 'hash:/etc/postfix/sender_canonical',
        'POSTMAP_sender_canonical': '@example.com noreply@example.com',
    })

    assert postconf(relay, 'sender_canonical_maps') == 'hash:/etc/postfix/sender_canonical'
    # The ones that were not set still point at postsrsd.
    assert postconf(relay, 'recipient_canonical_maps') == 'tcp:127.0.0.1:10002'


@pytest.fixture
def shared_srs_relay(postfix_shared):
    """Rewriting relay shared by the tests that only read it back."""
    return postfix_shared(env={'POSTSRSD_SRS_DOMAIN': SRS_DOMAIN})


def test_a_bounce_to_a_rewritten_address_finds_the_original_sender(shared_srs_relay,
                                                                   mailpit):
    """The other half of rewriting, and the reason it is reversible.

    A receiver that bounces a forwarded message answers the rewritten
    envelope sender, so that address has to lead back to the person who
    sent the message. Without this the rewriting would swallow every bounce.
    """
    send(shared_srs_relay, sender='sender@example.com', subject='forwarded')
    rewritten = mailpit.wait_for_message('forwarded')['ReturnPath']

    send(shared_srs_relay, sender='', recipients=(rewritten,), subject='the bounce')

    message = mailpit.wait_for_message('the bounce')

    assert [to['Address'] for to in message['Bcc']] == ['sender@example.com']


def test_postsrsd_is_only_reachable_from_the_container(shared_srs_relay):
    """The rewriting sockets are lookup tables with no authentication.

    Anything that can reach them can have an address signed with this
    relay's secret, so they listen on the loopback address only.
    """
    sockets = {(address, port) for address, port in listening_sockets(shared_srs_relay)
               if port in (10001, 10002)}

    assert sockets == {('127.0.0.1', 10001), ('127.0.0.1', 10002)}


def test_mail_that_is_already_rewritten_is_left_alone(shared_srs_relay, mailpit):
    """Rewriting a rewritten address would make the chain longer at every
    hop, and postsrsd stops at its own domain."""
    send(shared_srs_relay, sender=f'noreply@{SRS_DOMAIN}', subject='own domain')

    assert mailpit.wait_for_message('own domain')['ReturnPath'] == \
        f'noreply@{SRS_DOMAIN}'


def test_the_separator_can_be_changed(postfix_shared, mailpit):
    """SRS_SEPARATOR is one of the settings the README says can be passed
    through, and it changes the address every receiver sees."""
    relay = postfix_shared(env={'POSTSRSD_SRS_DOMAIN': SRS_DOMAIN,
                                'POSTSRSD_SRS_SEPARATOR': '+'})

    send(relay, sender='sender@example.com', subject='another separator')

    assert mailpit.wait_for_message('another separator')['ReturnPath'].startswith('SRS0+')


def test_several_domains_can_be_excluded_at_once(postfix_shared, mailpit):
    """The README's own example is a list, not a single domain."""
    relay = postfix_shared(env={
        'POSTSRSD_SRS_DOMAIN': SRS_DOMAIN,
        'POSTSRSD_SRS_EXCLUDE_DOMAINS': 'first.example,second.example',
    })

    send(relay, sender='sender@first.example', subject='first excluded')
    send(relay, sender='sender@second.example', subject='second excluded')
    send(relay, sender='sender@third.example', subject='not excluded')

    assert mailpit.wait_for_message('first excluded')['ReturnPath'] == \
        'sender@first.example'
    assert mailpit.wait_for_message('second excluded')['ReturnPath'] == \
        'sender@second.example'
    assert mailpit.wait_for_message('not excluded')['ReturnPath'].startswith('SRS0=')


def test_every_postsrsd_variable_reaches_the_daemon(postfix_shared):
    """The generated block is what /etc/default/postsrsd is read for."""
    relay = postfix_shared(env={
        'POSTSRSD_SRS_DOMAIN': SRS_DOMAIN,
        'POSTSRSD_SRS_HASHLENGTH': '8',
        'POSTSRSD_SRS_HASHMIN': '6',
    })

    generated = container_exec(relay, ["cat", "/etc/default/postsrsd"]).split(
        GENERATED_MARKER)[1]

    assert sorted(generated.split()) == [
        f'SRS_DOMAIN={SRS_DOMAIN}', 'SRS_HASHLENGTH=8', 'SRS_HASHMIN=6']


@pytest.mark.xfail(reason="known defect: the value is written unquoted into a "
                          "file the init script sources", strict=True)
def test_a_setting_that_needs_a_space_can_be_passed_through(postfix_factory):
    """postsrsd's own extra options are documented as a list.

    /etc/default/postsrsd documents SRS_EXTRA_OPTIONS with "-A" and "-t<n>",
    which is two words as soon as both are wanted. The file is sourced, so
    an unquoted value makes the shell run the second word as a command, the
    init script exits and the container refuses to start.
    """
    relay = postfix_factory(env={'POSTSRSD_SRS_DOMAIN': SRS_DOMAIN,
                                 'POSTSRSD_SRS_EXTRA_OPTIONS': '-A -t60'})

    assert process_running(relay, 'postsrsd')
